ARG GO_VERSION=1.14.2
ARG ALPINE_VERSION=3.11
ARG CHECKSTYLE_MERGER_VERSION=

# ---- App container
FROM golang:${GO_VERSION}-alpine${ALPINE_VERSION}
WORKDIR /
COPY checkstyle-merger /checkstyle-merger
ENTRYPOINT ./checkstyle-merger
